from __future__ import annotations

from PySide6.QtCore import Qt
from PySide6.QtWidgets import QComboBox, QFrame, QGridLayout, QHBoxLayout, QLabel, QLineEdit, QPushButton, QSpinBox, QVBoxLayout

from monitor_noticias.ui.refined_base import BasePage, ProxyTestThread, ToggleSwitch, card, dangerous, heading, secondary


class AutomationBlock(QFrame):
    def __init__(self,title:str,subtitle:str,color:str,run_cb,interval_options:list[str]|None=None):
        super().__init__(); self.setObjectName("techCard"); self.run_cb=run_cb
        root=QVBoxLayout(self); root.setContentsMargins(16,12,16,12); root.setSpacing(8)
        top=QHBoxLayout(); icon=QLabel("▤" if title=="Notícias" else "▣" if title=="Demandas" else "▶"); icon.setFixedSize(48,48); icon.setAlignment(Qt.AlignmentFlag.AlignCenter); icon.setStyleSheet(f"color:{color};background:#063052;border:1px solid {color};border-radius:9px;font-size:23px;"); top.addWidget(icon); titles=QVBoxLayout(); t=QLabel(title); t.setObjectName("sectionTitle"); sub=QLabel(subtitle); sub.setObjectName("smallText"); titles.addWidget(t); titles.addWidget(sub); top.addLayout(titles,1); self.badge=QLabel("automático ativo"); self.badge.setStyleSheet("color:#14e69a;border:1px solid #0bb47b;border-radius:7px;padding:4px 8px;font-weight:700;"); top.addWidget(self.badge); self.toggle=ToggleSwitch(); top.addWidget(self.toggle); self.run=secondary(QPushButton("▶  Executar agora")); self.run.setEnabled(False); self.run.setToolTip("Representação visual da referência; a tela Configurações atual não possui este callback."); top.addWidget(self.run); root.addLayout(top)
        self.interval=QComboBox()
        if interval_options: self.interval.addItems(interval_options); ir=QHBoxLayout(); label=QLabel("Frequência"); label.setObjectName("smallTitle"); ir.addWidget(label); ir.addWidget(self.interval); ir.addStretch(); root.addLayout(ir)


class SettingsPage(BasePage):
    def __init__(self,controller):
        super().__init__(controller); self._proxy_thread=None
        proxy,pl=card("techCard",(18,14,18,14),9); ph=QHBoxLayout(); lock=QLabel("▣"); lock.setFixedSize(56,56); lock.setAlignment(Qt.AlignmentFlag.AlignCenter); lock.setStyleSheet("color:#56cbff;background:#075884;border:1px solid #0a86b8;border-radius:10px;font-size:25px;"); ph.addWidget(lock); titles=QVBoxLayout(); title=QLabel("Configuração de proxy"); title.setObjectName("sectionTitle"); self.proxy_description=QLabel(); self.proxy_description.setObjectName("smallText"); titles.addWidget(title); titles.addWidget(self.proxy_description); ph.addLayout(titles,1); self.proxy_state=QLabel(); self.proxy_state.setObjectName("smallTitle"); ph.addWidget(self.proxy_state); self.proxy_enabled=ToggleSwitch(); ph.addWidget(self.proxy_enabled); pl.addLayout(ph)
        fields=QGridLayout(); self.host=QLineEdit(); self.port=QSpinBox(); self.port.setRange(1,65535); self.user=QLineEdit(); self.user.setPlaceholderText("Usuário do proxy"); self.password=QLineEdit(); self.password.setEchoMode(QLineEdit.EchoMode.Password); self.password.setPlaceholderText("Senha do proxy"); fields.addWidget(QLabel("Servidor"),0,0); fields.addWidget(QLabel("Porta"),0,1); fields.addWidget(QLabel("Usuário"),0,2); fields.addWidget(QLabel("Senha"),0,3); fields.addWidget(self.host,1,0); fields.addWidget(self.port,1,1); fields.addWidget(self.user,1,2); fields.addWidget(self.password,1,3); self.save_proxy=QPushButton("✓  Salvar e aplicar"); self.test_proxy=secondary(QPushButton("⌁  Testar conexão")); fields.addWidget(self.save_proxy,1,4); fields.addWidget(self.test_proxy,1,5); pl.addLayout(fields); self.proxy_message=QLabel(); self.proxy_message.setObjectName("smallText"); self.proxy_message.setWordWrap(True); pl.addWidget(self.proxy_message); self.root.addWidget(proxy)
        auto,al=card("techCard",(18,14,18,14),8); ah=QHBoxLayout(); clock=QLabel("◷"); clock.setStyleSheet("color:#28b7ff;font-size:31px;"); ah.addWidget(clock); ab=QVBoxLayout(); tt=QLabel("Buscas automáticas"); tt.setObjectName("sectionTitle"); ss=QLabel("Notícias, Demandas e Vídeos funcionam de forma independente."); ss.setObjectName("smallText"); ab.addWidget(tt); ab.addWidget(ss); ah.addLayout(ab,1); ctl=QVBoxLayout(); ct=QLabel("Controle geral"); ct.setObjectName("smallText"); self.general=ToggleSwitch(); ctl.addWidget(ct); ctl.addWidget(self.general); ah.addLayout(ctl); al.addLayout(ah); sep=QFrame(); sep.setFixedHeight(1); sep.setStyleSheet("background:#0b5f85;border:0;"); al.addWidget(sep); sr=QHBoxLayout(); pc=QLabel("▰"); pc.setStyleSheet("color:#2ebaff;font-size:24px;"); sr.addWidget(pc); stb=QVBoxLayout(); st=QLabel("Iniciar Monitor de Notícias com o Windows"); st.setObjectName("smallTitle"); st2=QLabel("Inicialização automática ao entrar no sistema."); st2.setObjectName("smallText"); stb.addWidget(st); stb.addWidget(st2); sr.addLayout(stb,1); self.startup=ToggleSwitch(); sr.addWidget(self.startup); al.addLayout(sr); self.root.addWidget(auto)
        self.news_block=AutomationBlock("Notícias","Varredura automática das fontes selecionadas","#38c9ff",controller.search_news,["15","30","45","60","120"]); self.dem_block=AutomationBlock("Demandas","Pesquisa automática de todas as demandas ativas","#ffc21a",controller.search_all_demands,["15","30","45","60","120"]); self.video_block=AutomationBlock("Vídeos","Varredura automática das fontes de vídeo","#b45cff",controller.search_videos,None); self.root.addWidget(self.news_block); self.root.addWidget(self.dem_block); self.root.addWidget(self.video_block)
        vrow=QHBoxLayout(); vl=QLabel("Horários dos vídeos"); vl.setObjectName("smallTitle"); self.video_times=QLineEdit(); self.video_times.setPlaceholderText("08:00, 12:00, 15:00, 19:00, 21:00"); self.apply_auto=QPushButton("✓  Aplicar automação"); vrow.addWidget(vl); vrow.addWidget(self.video_times,1); vrow.addWidget(self.apply_auto); self.root.addLayout(vrow)
        self.save_proxy.clicked.connect(self._save_proxy); self.test_proxy.clicked.connect(self._test_proxy); self.apply_auto.clicked.connect(self._apply_auto); self.startup.toggled.connect(self._startup)
    def _save_proxy(self):
        cfg=self.controller.save_proxy(self.proxy_enabled.isChecked(),self.host.text(),self.port.value(),self.user.text(),self.password.text()); self.proxy_message.setText("Configuração salva e aplicada."); self.password.clear(); self.host.setText(cfg.host); self.port.setValue(cfg.port)
    def _test_proxy(self):
        self.test_proxy.setEnabled(False); self.proxy_message.setText("Testando conexão..."); self._proxy_thread=ProxyTestThread(self.controller); self._proxy_thread.completed.connect(self._proxy_done); self._proxy_thread.start()
    def _proxy_done(self,ok,text): self.proxy_message.setText(text); self.test_proxy.setEnabled(True); self._proxy_thread=None
    def _startup(self,checked):
        ok=self.controller.set_start_with_windows(checked)
        if checked and not ok:self.startup.setToolTip("Executável empacotado ainda não existe; preferência preservada para o portable final.")
    def _apply_auto(self):
        s=self.controller.automation_settings; s.automatic_monitoring=self.general.isChecked(); s.news_automatic=self.news_block.toggle.isChecked(); s.demand_automatic=self.dem_block.toggle.isChecked(); s.video_automatic=self.video_block.toggle.isChecked(); s.news_interval_minutes=int(self.news_block.interval.currentText()); s.demand_interval_minutes=int(self.dem_block.interval.currentText()); s.video_schedule_times={x.strip() for x in self.video_times.text().split(',') if x.strip()}; self.controller.refresh()
    def refresh(self,state):
        cfg=self.controller.proxy_config; self.proxy_enabled.blockSignals(True); self.proxy_enabled.setChecked(cfg.enabled); self.proxy_enabled._sync(cfg.enabled); self.proxy_enabled.blockSignals(False); self.proxy_state.setText("Ativado" if cfg.enabled else "Desativado"); self.proxy_description.setText(f"Servidor fixo {cfg.host}:{cfg.port}. Informe usuário e senha para autenticação." if cfg.host else "Configure o servidor proxy já suportado pelo aplicativo."); self.host.setText(cfg.host); self.port.setValue(cfg.port); self.user.setText(cfg.username)
        s=self.controller.automation_settings
        for widget,value in ((self.general,s.automatic_monitoring),(self.news_block.toggle,s.news_automatic),(self.dem_block.toggle,s.demand_automatic),(self.video_block.toggle,s.video_automatic)):
            widget.blockSignals(True); widget.setChecked(value); widget._sync(value); widget.blockSignals(False)
        self.news_block.badge.setText("automático ativo" if s.news_automatic else "automático pausado"); self.dem_block.badge.setText("automático ativo" if s.demand_automatic else "automático pausado"); self.video_block.badge.setText("automático ativo" if s.video_automatic else "automático pausado")
        self.news_block.interval.setCurrentText(str(s.news_interval_minutes)); self.dem_block.interval.setCurrentText(str(s.demand_interval_minutes)); self.video_times.setText(", ".join(sorted(s.video_schedule_times))); self.startup.blockSignals(True); self.startup.setChecked(self.controller.start_with_windows); self.startup._sync(self.controller.start_with_windows); self.startup.blockSignals(False)


class StopPage(BasePage):
    def __init__(self,controller):
        super().__init__(controller); self.news_status=QLabel(); self.video_status=QLabel(); self.news=dangerous(QPushButton("■  Parar notícias/demandas")); self.video=dangerous(QPushButton("■  Parar vídeos")); self.all=dangerous(QPushButton("■  Parar tudo")); self.news.clicked.connect(controller.stop_news_search); self.video.clicked.connect(controller.stop_video_search); self.all.clicked.connect(controller.stop_all_searches)
        for title,label,button in (("Notícias e demandas",self.news_status,self.news),("Vídeos",self.video_status,self.video)):
            frame,layout=card("techCard",(18,16,18,16),8); layout.addWidget(heading(title,"Interrompa somente a execução atual; a automação permanece configurada.")); label.setObjectName("smallText"); layout.addWidget(label); layout.addWidget(button,0,Qt.AlignmentFlag.AlignLeft); self.root.addWidget(frame)
        self.root.addWidget(self.all,0,Qt.AlignmentFlag.AlignLeft); self.root.addStretch()
    def refresh(self,state): self.news_status.setText(state.status if state.news_busy else "Nenhuma busca em andamento"); self.video_status.setText(state.video_status if state.video_busy else "Nenhuma busca em andamento"); self.news.setEnabled(state.news_busy); self.video.setEnabled(state.video_busy); self.all.setEnabled(state.news_busy or state.video_busy)
